const moiveslist = [
  {
    id: 1,
    name: "Akaal",
    posterurl: "Movies posters/Akaal.jpg",
    type: "Thrill, Action",
    starcast: "Gippy Grewal, Nimrat Khaira, Gurpreet Ghuggi, ",
    Director: "",
    releasedate: "Apr-10-2025",
  },
  {
    id: 2,
    name: "Badnaam",
    posterurl: "Movies posters/Badnaam.jpg",
    type: "Action, Dharama",
    starcast: "Jayy Randhawa, Jasmin Bhasin",
    Director: "",
    releasedate: "Feb-28-2025",
  },
  {
    id: 3,
    name: "Hoshiar Singh",
    posterurl: "Movies posters/Hoshiar Singh.jpg",
    type: "Dharama comedy",
    starcast: "Simi Chahal, Satinder Sartaaj",
    director: "Uday Partap Singh",
    releasedate: "Feb-07-2025",
  },
  {
    id: 4,
    name: "Jatt Nuu Chudail Takri",
    posterurl: "Movies posters/Jatt Nuu Chudail Takri.jpg",
    type: "Dharama Comedy",
    starcast: "Gippy Grewal, Jasmin Bhasin",
    director: "Vikash Vashisht",
    releasedate: "Mar-15-2024",
  },
  {
    id: 5,
    name: "KHADPANCH",
    posterurl: "Movies posters/KHADPANCH.jpeg",
    type: "Dharama",
    starcast: "Amrit Amby, Butta Badbar, Dhutta Pindi Ala",
    director: "Rabby Tiwana",
    releasedate: "Jan-25-2025",
  },
  {
    id: 6,
    name: "Majhail",
    posterurl: "Movies posters/Majhail.jpg",
    type: "Action",
    starcast: "Dev Kharoud, Guggu Gill, Roop Gill",
    director: "Dheeraj Kedarnath Rattan",
    releasedate: "Jan-31-2025",
  },
  {
    id: 7,
    name: "Oye Bhole Oye",
    posterurl: "Movies posters/Oye Bhole Oye.jpg",
    type: "Comedy",
    starcast: "Jagjeet Shandu, Irwin Meet Kaur, Soumya",
    director: "Varinder Ramghria",
    releasedate: "Feb-16-2024",
  },
  {
    id: 8,
    name: "Parahuna 2",
    posterurl: "Movies posters/Parahuna 2.jpeg",
    type: "Comedy",
    starcast: "Ranjit Bawa, Aditi Sharma, Gurpreet Ghuggi",
    director: "Ksshitji Chaudhary",
    releasedate: "Mar-29-2024",
  },
  {
    id: 9,
    name: "Sikander 3",
    posterurl: "Movies posters/Sikander 3.jpg",
    type: "Thrill",
    starcast: "Kartar Cheema",
    director: "Manav Shah",
    releasedate: "July-18-2025",
  },
  {
    id: 10,
    name: "Warning 2",
    posterurl: "Movies posters/Warning 2.jpg",
    type: "Action",
    starcast: "Gippy Grewal, Prince Kawaljit Singh",
    director: "Amar Hundal",
    releasedate: "Feb-02-2024",
  },
  //   {
  //     id: 11,
  //     name: "",
  //     posterurl: "",
  //     type: "",
  //     starcast: "",
  //     director: "",
  //     releasedate: "",
  //   },
];

export { moiveslist };
